spring.application.name=GatchBackend
spring.mongodb.uri=${MONGO_URI}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GATCHMAILUSERNAME}
spring.mail.password=${GATCHMAILPASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${SECRET_JWT}